<a href="https://colab.research.google.com/github/harshsojitra007/CE132_ML_Labs/blob/main/CE132_ML_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practice

In [ ]:
import numpy as np
import random as rand

x = [1, 2, 3]
print(x, "Type: ", type(x))

arr = np.array(x)
print(arr, "Type: ", type(arr))

print("Sum of list: ", x + x) # It will concatenate the list
print("Sum of array: ", arr + arr) # Addition of two list will be performed

x = ["Harsh", "Sojitra"]
print(x * 2) # ['Harsh', 'Sojitra', 'Harsh', 'Sojitra']

arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[1, 5], [2, 6], [1, 7]])

# size must be same of both matrix for addition
# print(arr1 + arr2)
# print(np.add(arr1, arr2))

# no. of rows in one matrix and no. of columns in another matrix must be same
print(np.dot(arr1, arr2))
print(arr1.dot(arr2))
print(arr1 @ arr2)

print(arr1.T)

arr1 = np.array([[1, 9], [2, 5]])
arr2 = np.array([[2, 6], [1, 4]])

# 1 9     2 6
#      *
# 2 5     1 4

print(arr1 @ arr2)
print(arr1 * arr2)

print(np.linalg.norm(arr1))

arr2 = np.array([["Harsh Sojitra"]])
for a, b  in zip(arr1, arr2):
  print(a, b)

[1, 2, 3] Type:  <class 'list'>
[1 2 3] Type:  <class 'numpy.ndarray'>
Sum of list:  [1, 2, 3, 1, 2, 3]
Sum of array:  [2 4 6]
['Harsh', 'Sojitra', 'Harsh', 'Sojitra']
[[ 8 38]
 [16 74]]
[[ 8 38]
 [16 74]]
[[ 8 38]
 [16 74]]
[[1 3]
 [2 4]
 [3 5]]
[[11 42]
 [ 9 32]]
[[ 2 54]
 [ 2 20]]
10.535653752852738
[1 9] ['Harsh Sojitra']


Exercise

In [ ]:
import random as rand
import numpy as np

arr1 = [[0 for _ in range(5)] for _ in range(4)]

for i in range(4):
  for j in range(5):
    arr1[i][j] = rand.randint(0, 100)

arr1 = np.array(arr1)

arr2 = [[0 for _ in range(4)] for _ in range(5)]
for i in range(5):
  for j in range(4):
    arr2[i][j] = rand.randint(0, 100)

arr2 = np.array(arr2)

print("Multiplication of matrices is,")
print(np.dot(arr1, arr2))

# For element wise matrix multiplication size of both the matrices must be same so it is not possible for give matrices
# An error will be generated when multiplication is performed
# ValueError: operands could not be broadcast together with shapes (4,5) (5,4)
# print(np.multiply(arr1, arr2))

print("\nMean of arr1 is, ", np.mean(arr1))
print("\nMedian of arr1 is, ", np.median(arr1))
print("\nTranspose of arr1 is,\n", arr1.T)

arr3 = np.random.randint(100, size=(3, 3))
arr3 = np.array(arr3)
print("\nSquare Matrix [arr3]\n", arr3)

det = np.linalg.det
print("\nDeterminant of arr3 is, ", det(arr3))

secondColumn = []
for row in arr1:
  secondColumn.append(row[2])
print("\nSecond Column of each row: ", secondColumn, "\n")

data = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/mtcars.csv", delimiter=",", dtype=str, usecols=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
manipulatedData = [[0 for _ in range(len(data[0]))] for _ in range(len(data))]

for i in range(1, len(data)):
  for j in range(len(data[0])):
    manipulatedData[i - 1][j] = float(data[i][j])

manipulatedData = np.array(manipulatedData)

# Mean Centered by Row
print("\n\nMean Centered by Row:\n")
centerByRow = manipulatedData - np.mean(manipulatedData, axis=0)
print(centerByRow)

# Mean Centered by Column
print("\n\nMean Centered by Column:\n")
centerByColumn = manipulatedData.T - np.mean(manipulatedData, axis=1)
centerByColumn = centerByColumn.T

print(centerByColumn)

Multiplication of matrices is,
[[ 8674  9392 12512 10683]
 [ 5936  7500 10728  8497]
 [20280  8415  4443 14839]
 [ 7305  4673  7318  7572]]

Mean of arr1 is,  41.35

Median of arr1 is,  32.0

Transpose of arr1 is,
 [[  3  31  81  49]
 [ 14   5 100  26]
 [ 77  30  76  14]
 [ 73  91   1  37]
 [ 51  17  18  33]]

Square Matrix [arr3]
 [[87 74 19]
 [89 44 89]
 [ 3 91 13]]

Determinant of arr3 is,  -569335.9999999993

Second Column of each row:  [77, 30, 76, 14] 



Mean Centered by Row:

[[ 1.51818182e+00  0.00000000e+00 -6.37303030e+01 -3.22424242e+01
   4.12424242e-01 -4.99757576e-01 -8.47878788e-01 -4.24242424e-01
   6.06060606e-01  4.24242424e-01]
 [ 1.51818182e+00  0.00000000e+00 -6.37303030e+01 -3.22424242e+01
   4.12424242e-01 -2.44757576e-01 -2.87878788e-01 -4.24242424e-01
   6.06060606e-01  4.24242424e-01]
 [ 3.31818182e+00 -2.00000000e+00 -1.15730303e+02 -4.92424242e+01
   3.62424242e-01 -7.99757576e-01  1.30212121e+00  5.75757576e-01
   6.06060606e-01  4.24242424e-01]
 [ 1.91818