<a href="https://colab.research.google.com/github/harshsojitra007/CE132_ML_Labs/blob/main/ML_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Data_for_Transformation.csv")
newX = data.iloc[:, 1:3].values

print("Columns to transform\n\n", newX)

minMaxScaler = MinMaxScaler()
standardScaler = StandardScaler()

scaledX = minMaxScaler.fit_transform(newX)
standardizedX = standardScaler.fit_transform(newX)

print("\nScaled data\n\n", scaledX)
print("\nStandardized data\n\n", standardizedX)

dataCategory = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Data_for_Categorical_Values.csv")
print('\n')
dataCategory.describe()

newX = dataCategory.iloc[ : , :-1].values
dataCategoryCp = dataCategory

labelEncoder = LabelEncoder()
newX[ : , 0] = labelEncoder.fit_transform(newX[ : , 0])
print(newX)

dummyCountries = pd.get_dummies(dataCategory["Country"])
print('\n', dummyCountries)

dataCategory = dataCategory.drop(['Country', 'Purchased'], axis=1)
print('\nNew Dataset\n', dataCategory)
dataCategory = pd.concat([dummyCountries, dataCategory], axis=1)
print('\nNew Dataset\n', dataCategory)

oneHotEncoder = OneHotEncoder()
x = oneHotEncoder.fit_transform(dataCategoryCp.Country.values.reshape(-1,1)).toarray()
print('\n', x)

dfOneHot = pd.DataFrame(x, columns=["Country_" + str(int(i)) for i in range(dataCategoryCp.shape[1] - 1)])
dataFrame = pd.concat([dfOneHot, dataCategoryCp], axis=1)
dataFrame = dataFrame.drop(['Country'], axis=1)
print('\n', dataFrame)

dataMiss = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Data_for_Missing_Values.csv")
print('\n')
dataMiss.describe()

dataMiss.dropna(axis=0, how="all", inplace=True)
print('\nNew Dataset for missed data\n\n', dataMiss)

updatedDataMiss = dataMiss
updatedDataMiss['Age'] = updatedDataMiss['Age'].fillna(updatedDataMiss['Age'].mean())
print('\nReplace Null Age with mean\n\n', updatedDataMiss)

updatedDataMiss['Salary'] = updatedDataMiss['Salary'].fillna(updatedDataMiss['Salary'].mean())
print('\nReplace Null Salary with mean\n\n', updatedDataMiss)

Columns to transform

 [[   44 72000]
 [   27 48000]
 [   30 54000]
 [   38 61000]
 [   40 68000]
 [   35 58000]
 [   39 52000]
 [   48 79000]
 [   50 83000]
 [   37 67000]
 [   45 55000]]

Scaled data

 [[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739 0.57142857]
 [0.34782609 0.28571429]
 [0.52173913 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]
 [0.7826087  0.2       ]]

Standardized data

 [[ 0.68188156  0.79548755]
 [-1.81835082 -1.41513049]
 [-1.37713334 -0.86247598]
 [-0.2005534  -0.21771238]
 [ 0.09359159  0.42705121]
 [-0.64177088 -0.49403964]
 [-0.05348091 -1.04669415]
 [ 1.27017153  1.44025115]
 [ 1.56431652  1.80868749]
 [-0.34762589  0.33494213]
 [ 0.82895405 -0.77036689]]


[[0 44 72000]
 [2 27 48000]
 [1 30 54000]
 [2 38 61000]
 [1 40 68000]
 [0 35 58000]
 [2 39 52000]
 [0 48 79000]
 [1 50 83000]
 [0 37 67000]
 [2 45 55000]]

     France  Germany  Spain
0        1     